### PR TITLE
update petsc

### PR DESCRIPTION
**Pull request by tjhei**
this old version does not compile with newer MPI 3.0:
```
/home/heister/shared-dealii/dealii-v9.1.1/tmp/build/petsc-
lite-3.7.6/src/sys/objects/init.c:412:40: error: ‘MPI_Handler_function’
undeclared
```
so update to 3.11.3 (latest stable).

### CODE REVIEW

**Comment by koecher** [comment]
Nice. We had the old petsc and slepc for a long time. Thank you.
