### ISSUE TITLE
OpenBlas 0.3.13 fails to build with GNU 7.1.0 compilers (Stampede2)

### ISSUE THREAD

**Issue by naliboff** [dealii/candi#258]
The default version of OpenBlas with the current version of Candi is 0.3.13. When building this version of OpenBlas on Stampede2 with GNU compilers (7.1.0), a series of errors is thrown of the following nature:
`../kernel/x86_64/dasum_microk_skylakex-2.c:42:38: error: incompatible type for argument 1 of ‘_mm512_abs_pd’`

This error is documented elsewhere ([for example](https://github.com/xianyi/OpenBLAS/issues/2949)) and appears to be related to [a bug in the GNU compilers](https://gcc.gnu.org/legacy-ml/gcc-patches/2018-01/msg01962.html).

Reverting to OpenBlas 0.3.7 produced no errors and allowed a successful build of trillions, deal.II 9.3.0, and ASPECT.

I'm not sure this is worth updating as the fix is documented on the [ASPECT wiki](https://github.com/geodynamics/aspect/wiki/Compiling-and-Running-ASPECT-on-TACC-Stampede2) and newer GNU compilers are now available on Stampede2, on which the issue may not exist.

**Comment by naliboff** [comment]
For reference, the same error occurs with gcc 9.1.0

**Comment by tjhei** [comment]
Are 7.1 and 9.1 the newest compilers installed on stampede2? Those are quite old.
I would agree that we don't do anything here and just point people to this issue to work around the issue.

**Comment by naliboff** [comment]
> Are 7.1 and 9.1 the newest compilers installed on stampede2? 
These are the newest GCC compilers. There are much newer intel compilers, but I have still not been able to successfully build deal.II with the intel compilers on Stampede2 (I last tried 6-12 months ago). Should we revisit this? I recall one the Stampede2 folks was trying recently, as he posted on the ASPECT forums. Given you have compiled on Frontera, hopefully it is possible without a major effort.

> I would agree that we don't do anything here and just point people to this issue to work around the issue.
👍
